version: '3.3'
services:
  dsp:
    restart: always
    container_name: "marquee-dsp"
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "30678:30678"
  # server:
  #   restart: always
  #   container_name: "marquee-server"
  #   build:
  #     context: ./backend
  #     dockerfile: Dockerfile
  #   ports:
  #     - "8099:8099"
  #   environment:
  #     - PORT=8099
