version: '3.3'
services:
  dsp:
    restart: always
    container_name: "template-dsp"
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "5173:5173"

  server:
    restart: always
    container_name: "template-server"
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - PORT=8080
